# Oracle Database Connection
spring.datasource.url=jdbc:oracle:thin:@fsktmdbora.upm.edu.my:1521:FSKTM
spring.datasource.username=D231302
spring.datasource.password=231302
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true